### ISSUE TITLE
카드 서비스의 테스트 추가

### ISSUE THREAD

**Issue by GounKim** [DHKH-null29/linky_way_back#121]
## 요구사항
카드 서비스의 테스트를 수정하고 테스트가 없는 카드 서비스에는 테스트를 추가한다.

**Comment by E1psycongr00** [comment]
고운님 지금 진행 상황이 어느정도인지 파악하기 힘들어서 이슈나 지금까지 하신 부분 PR좀 부탁드리겠습니다...  페이징 처리 작업을 하려고 하는데 카드, 소셜 조회에 대해서 어느정도 손을 봐야 되서...
