### ISSUE TITLE
페이징 처리 및 생성 횟수 제한

### ISSUE THREAD

**Issue by E1psycongr00** [DHKH-null29/linky_way_back#136]
# 요구사항

- 카드 조회와 소셜 페이지 페이징 처리 구현 (무한 스크롤 로딩에 필요)
- 태그와 폴더의 경우 최대 갯수 제한 (최대 갯수 초과 시 생성 불가)

**Comment by pds0309** [comment]
아직 진행안하셨으면 커서페이징으로 부탁드려도 될까요?  오프셋 페이징으로 하면 개인페이지에서도 이미 있던 목록 추가,삭제 시 겹처서 나올 수 있다는걸 간과하고있었네요

**Comment by E1psycongr00** [comment]
> 아직 진행안하셨으면 커서페이징으로 부탁드려도 될까요? 오프셋 페이징으로 하면 개인페이지에서도 이미 있던 목록 추가,삭제 시 겹처서 나올 수 있다는걸 간과하고있었네요

Pageable이 내부적으로 커서페이징인지 오프셋 페이징인지 저도 확실히 모르는데 확인해보고 아니면 따로 적용해보겠습니다.

**Comment by pds0309** [comment]
오프셋페이징입니다

**Comment by E1psycongr00** [comment]
아 그러면 다른 방식을 써야겠네요... 감사합니다.
