### ISSUE TITLE
예외처리와 핸들링 관련

### ISSUE THREAD

**Issue by E1psycongr00** [DHKH-null29/linky_way_back#21]
- 커스텀 예외의 경우 비즈니스 로직 예외 처리에 경우만 사용하자
    - ex) 논리적으로 맞지 않는 경우 throw new 를 이용해 처리해야 하는 경우
    - Http, URI에 관련된 예외는 주어진 예외로 핸들링
- URI에 404 예외처리 핸들링 안한 것 있음. 해결하겠음.
- 비즈니스 로직 예외 2가지로 나눔
    - ResourceNotFoundException (조회시 없는 경우) 404
    - ResourceConflictException (중복시 삽입, 없는데 수정, 삭제하는 경우 ) 409

**Comment by pds0309** [comment]
[400 vs 404](https://hyeon9mak.github.io/400-bad-request-vs-404-not-found/)

**Comment by E1psycongr00** [comment]
저는 위에 블로그 내용이 400에 대해서 너무 관대하게 생각하는 것 같아 조회 시 400에 쓰는 것에 대해서는 이해하기 어렵습니다. 404에 대해 해석해보면  링크 처리 시 뿐만 아니라 db자원이 없는 경우도 충분히 사용 할 수 있다고 생각합니다. 둘 다 자원이기 때문입니다.

400에 대해 정의를 살펴보면 클라이언트에 대한 요청에 대해서 서버가 처리 할 수 없거나 처리하지 않는다는 것입니다.

https://developer.mozilla.org/ko/docs/Web/HTTP/Status/400
https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.3

만약 잘못된 형태에 대해서 서버(서비스)가 직접 그 요청을 처리한다면 500이 된다고 생각합니다. 그러면 서버 입장에선 500을 막기 위해서 예외 처리를 하고 409를 보내야 하기 때문입니다.

제 생각을 정리해서 말씀드리면
dispatcher servlet이 URI 요청에 대해서 처리하거나 컨트롤러에서 검증 시 예외가 발생하면 400,
URI가 존재하지 않는 요청을 한 경우(데드링크 같은)  그리고 비즈니스 로직 조회시 예외가 발생한 경우 404,
내부적으로 처리 시 500에 위험성이 있는 비즈니스 로직은 개발자가 따로 예외 처리해서 409를 응답하도록 기준을 정했습니다.
