### ISSUE TITLE
Swagger 세팅 추가 및 시큐리티 관련 Issue

### ISSUE THREAD

**Issue by E1psycongr00** [DHKH-null29/linky_way_back#26]
## 변경점:

- Authorize 버튼을 누르면 인증 될 수 있게 Swagger 수정
- sql 디버깅 편하게 application 설정 파일 몇 가지 추가 및 수정

## 문제점

swagger 새로고침 요청시 10번 12번  jwt provider 10번 12번 호출되는 문제
![image](https://user-images.githubusercontent.com/39326175/169648668-f45a3ccf-df03-4862-ad9c-4f6150b55628.png)

h2-console 출력 안됨... security 설정이 /** 인데 왜 h2-console만 안되네요.. 명시적으로 /h2-console/**로 선언해도 적용이 안됩니다.
![image](https://user-images.githubusercontent.com/39326175/169649680-a657f774-7933-46ec-8d2d-aa05a2ba7372.png)

## 제안 사항(개인적인 의견):
- login도 controller에 맡겨두면 어떨까요...? 이 부분도 swagger-test 할 때 로그인도 한번에 하면 좋을 것 같기도 한데...( 근데 이 부분을 바꾼다고 하면 동석님 코드를 많이 바꿔야 할 것 같기도 해서 부담되시면 안하셔도 될 것 같아요.
- 의존성 문제:  Security의 여러 설정 부분이 MemberService에 의존하다 보니 구조를 변경 할 때 조금 부담이 되긴 합니다.

일단 feat/#26/swagger_setting 브랜치에 커밋 해두었습니다.

**Comment by E1psycongr00** [comment]
회원가입 기능도 그냥 혹시 몰라서 push 해뒀습니다.

**Comment by pds0309** [comment]
회원가입 해주셔서 감사합니다 테스트하기 편했네요. 

Authorize 버튼에 대한 인증도 아주 잘 진행됩니다. 감사합니다.

그 외에 작성해두신 문제는 모두 해결해왔습니다

<br>

### 문제1: Swagger 접속 시 jwt provider 다중호출 문제

<br>

**원인**

- Authorization Filter 의 경우 실행하며 등록될 때 SpringSecurity 에서의 정책과 무관하게 FilterChain 에 등록되어 매 요청마다 수행됨

- swagger 웹 문서 한 번 접속 시 내부적으로 수 회의 요청이 발생함(개발자도구 네트워크나 디버깅으로 확인해보세요!)

```

**예를 들면 다음과 같은 요청을 함**

/swagger-ui/index.html

/swagger-resources/configuration/ui

/swagger-resources/configuration/security

/swagger-resources

/v3/api-docs
``` 

<br>

**해결**

`shouldNotFilter` 메소드 재정의해서 구현

방법1 - 인가 필터 동작 방지할 정확한 요청 path 를 수집해 화이트리스트를 만들어 처리

방법2 - `/api` 로 시작하는 요청들을 제외하고는 인가 필터 동작 방지 시킴

**Comment by E1psycongr00** [comment]
오.. 정말 수고 많으셨습니다... 👍 👍

**Comment by pds0309** [comment]
### 문제2: H2-console 접속 안됨

현규님이 어떤 원인으로 접속이 안되었는지 정확히 알 수 없어 저의 상황에 빗대어 해결함

위의 `문제1`을 해결하고 난 뒤의 상황임

<br>

**문제**

- h2-console 접속 시 응답은 200으로 잘 나오나 내부적으로 UI가 구성이 되지 않으며 아래의 이미지와 같은 결과가 나옴

![h21](https://user-images.githubusercontent.com/76927397/169674022-a459d629-27ee-4db8-9095-d25bef30aeb8.JPG)


<br>

**해결**

- 개발자 도구에서 html 태그들을 확인해보니 `<frame>` 들로 구성되어있었고 요청 헤더를 보니 `X-Frame-Option` 이 `Deny` 였음

- SpringSecurity 설정에서 H2 요청 시 해당 옵션을 비활성화 해줌

**Comment by E1psycongr00** [comment]
오 저도 같은 문제였는데 .. 감사합니다.

**Comment by pds0309** [comment]
### 번외: 매 요청마다 `@ApiIgnore` 를 붙여야 하나?

**Swagger Configuration에 다음과 같은 설정을 붙이면 그럴 필요 없음**

```
 .ignoredParameterTypes(CurrentMember.class)

```

**Comment by E1psycongr00** [comment]
혹시 지금까지 한 것들 develop에 PR 해 주실 수 있나요?

**Comment by pds0309** [comment]
## 현규님 의견 확인 - 로그인도 Swagger 에

임의로 컨트롤러를 만들어 문서에 나오게 하는 방법이 있긴 합니다

```
    @PostMapping("/members/login")
    public ResponseEntity<Void> login(@RequestBody LoginRequest loginRequest) {

        return ResponseEntity.ok().build();
    }
```

저렇게만 해둬도 어차피 응답은 필터에서 끝나기 때문에 문서를 이용하는 사람 입장에서는 똑같습ㄴ다

**Comment by E1psycongr00** [comment]
아 그렇게 해도 되겠군요... 어짜피 필터에서 처리되겠지만 저렇게 해놓으면 members/login에 swagger가 요청을 할 수 있겠네요.

**Comment by pds0309** [comment]
만드신 feat/#26 브랜치로 그대로 진행할까요 아니면 따로 빼서할까요?

**Comment by E1psycongr00** [comment]
Security 수정이 많으면 따로 빼도 괜찮고 대부분  swagger 세팅 위주로만 바꼇다면 그대로 진행해도 될 것 같습니다.

**Comment by pds0309** [comment]
큰 수정사항은 없고 시큐리티 설정 1줄 추가와 현규님이 설정해두신 스웨거에 1줄 추가

그리고 인가 필터에 메소드 하나와 테스트 하나 추가 정도만 될 것 같습니다

**Comment by E1psycongr00** [comment]
아니면 하나 따로 빼도 상관은 없을 것 같아요.. 이 이슈는 트러블 슈팅으로 보내고

**Comment by pds0309** [comment]
현규님이 이미 브랜치에 해두신 작업은 어떡하나요?

**Comment by E1psycongr00** [comment]
어짜피 그 쪽에 커밋은 되어 있으니 삭제해도 될 것 같아요.

**Comment by pds0309** [comment]
develop 에 합쳐야 하는 부분드링라고 한다면 여기이슈에 묶고 pr하시는건 어떤가요?
그거 리뷰해서 합친다음  위에 말씀드렸던 것 pr해오겠습니다

사실 사소한거긴한데 몇 개 리뷰드리고 싶은게 있어서용 ㅋㅋㅋㅋ

**Comment by E1psycongr00** [comment]
아 그래도 괜찮습니다..!

**Comment by pds0309** [comment]
그럼 편의를 위해 미리 말씀드리겠습니다. 

Swagger Configuration 에서 
```
.securityContexts(Arrays.asList(securityContext()))
.securitySchemes(Arrays.asList(apiKey()))
```

다음과 같은 부분이 있는데 단일 길이 배열에 대해서는 `asSingletonList` 를 사용하는게 권장되는 걸로 알고 있습니다.

```
.securityContexts(Collections.singletonList(securityContext()))
.securitySchemes(Collections.singletonList(apiKey()))
```

> 불변임을 명시 , 고정길이, 메모리 절약

**Comment by pds0309** [comment]
`JoinRequest` 의 nickname의 경우 정규식 상 한글을 사용할 수 없습니다. 의도하신건지 궁금합니다

**Comment by E1psycongr00** [comment]
아 한글 쓴 부분이 있었나요?

**Comment by pds0309** [comment]
테스트하려고 회원가입 했는데 한글 닉네임은 사용이 불가능하더라고요 


`

**Comment by pds0309** [comment]
네네 그럼 편하게 하신부분 합쳐주세요! 

저도 이따가 해결했던 부분 pr 하겟슴다

**Comment by E1psycongr00** [comment]
👍

**Comment by E1psycongr00** [comment]
> 그럼 편의를 위해 미리 말씀드리겠습니다.
> 
> Swagger Configuration 에서
> 
> ```
> .securityContexts(Arrays.asList(securityContext()))
> .securitySchemes(Arrays.asList(apiKey()))
> ```
> 
> 다음과 같은 부분이 있는데 단일 길이 배열에 대해서는 `asSingletonList` 를 사용하는게 권장되는 걸로 알고 있습니다.
> 
> ```
> .securityContexts(Collections.singletonList(securityContext()))
> .securitySchemes(Collections.singletonList(apiKey()))
> ```
> 
> > 불변임을 명시 , 고정길이, 메모리 절약



> 그럼 편의를 위해 미리 말씀드리겠습니다.
> 
> Swagger Configuration 에서
> 
> ```
> .securityContexts(Arrays.asList(securityContext()))
> .securitySchemes(Arrays.asList(apiKey()))
> ```
> 
> 다음과 같은 부분이 있는데 단일 길이 배열에 대해서는 `asSingletonList` 를 사용하는게 권장되는 걸로 알고 있습니다.
> 
> ```
> .securityContexts(Collections.singletonList(securityContext()))
> .securitySchemes(Collections.singletonList(apiKey()))
> ```
> 
> > 불변임을 명시 , 고정길이, 메모리 절약

코드를 살펴보니 SingletonList은 객체를 그냥 끼워 넣기만 하고 asList는 분해해서 arrayList 로 재 생성 분배하는군요.. 거기에 불변으로 선언이 되어서 객체에 안정성도 보장이 되네요.. 좋은 내용 알아갑니다..!! 👍
