### ISSUE TITLE
Setter에 대한 문제 고민

### ISSUE THREAD

**Issue by E1psycongr00** [DHKH-null29/linky_way_back#29]
엔티티 생성자에서 id는 auto_increment라  초기화 할 수 없게 제가 막아 놨습니다. 그러나 기본 Jpa Repository를 이용해 엔티티 수정 작업을 하려니 조금 불편함이 느껴지기도 합니다.  해결 방안 3가지 정도 있는 것 같은데 의견이 궁금합니다. 다른 좋은 의견 있으면 주셔도 됩니다!!

-  엔티티에 Custom Setter 를 만든다.
- 생성자에서 id도 초기화 할 수 있게 한다.
- 모두 JQPL 또는 native 쿼리로 하드코딩한다. (이 부분은 생산성이 떨어 질 것 같습니다. 성능 면에선 괜찮긴 한데)

**Comment by GounKim** [comment]
수정 작업에 있어서 정확히 어떤 부분이 불편한지 작성해주시면 해결 방안을 고민하는데 도움이 될 것 같습니다.

**Comment by E1psycongr00** [comment]
![image](https://user-images.githubusercontent.com/39326175/168769402-d6352f78-4807-48ee-b80c-1bfb286c124d.png)

태그를 조회해서 확인하는데 조회한 태그를 재활용하려고 합니다.

1. 가져온 태그 엔티티에 setter를 이용해 수정만 하고 다시 save하는 방법.
2. 가져온 태그의 id를 기억하고 id 만 그대로 초기화하고 나머지는 입력값으로 초기화된 객체를 생성해서 save하는 방법
3. 1, 2 처럼 조회 필요없이 native 쿼리로 조회하는 방법(근데 jpa를 활용을 못해서 생산성이 떨어짐)

**Comment by E1psycongr00** [comment]
문제점
1. setter의 경우 최대한 안 쓰려고 해서 신경쓰입니다.
2. id는 auto_increment 때문에 의도치 못하게 id를 건드릴 수 있을 것 같아서 초기화 막아놨습니다. 이걸 허용하면 잠재적인 불안 요소가 생길 것 같습니다.
3. 그냥 어려움.. 힘듬.. 이거 한다고 하면 querydsl 쓰는걸 고려해봐야 할 것 같음.

**Comment by GounKim** [comment]
제 생각엔 가져온 태그 아이디를 기억하고 tag 정보는 따로 받아서 두 개의 정보를 모두 전달해 검색, 수정하는 것이 어떤가 싶네요

**Comment by pds0309** [comment]
setter 를 지양하라는게 아예 만들지 말라는 말이 아니라 필요한 부분에서만 만들라는 소리죠

수정이 필요한 부분에 대해서는 당연히 엔티티에 만들어야 된다고 생각합니다.

마이베티스 같이 단순히 쿼리만 매핑해주는게 아니고 영속화 된 객체를 직접 다뤄서 테이블에 변경을 줄 수 있는 환경이라면 그 환경을 이용하는게 맞다고 봅니다.

현규님이 올리신 코드 같은경우도 tag 엔티티 객체 자체에 변경을 주고 트랜잭션 나가면 알아서 반영되기 때문에 변경이 필요한 부분에 대해 set 메소드(의미있는 이름이면 더 좋을 듯) 를 만들어야 한다고 생각합니다

**Comment by E1psycongr00** [comment]
두 분 이야기 들어보니 setter 쪽을 쓰는 게 나을 것 같군요.. 의견 감사합니다~!

**Comment by pds0309** [comment]
필요한 부분에 대해서만 의미있는 이름으로 엔티티 수정 메소드를 만들어주는건 괜찮을 것 같습니다!

예를 들면  `changePassword` , `updateCard` 같은 형식이 될 것 같네요!
