### ISSUE TITLE
member  검증 테스트 문제

### ISSUE THREAD

**Issue by E1psycongr00** [DHKH-null29/linky_way_back#36]
@Email 부분이  중간에 @만 있으면 그냥 통과시킵니다. 고로 pattern을 이용한 방법으로 추후 해결 하겠습니다.
ex) @Email 사용 시  member@naver.com (0),  meber@asd21 (0)

#50 에서 해결

**Comment by pds0309** [comment]
네 맞아요 이메일 검증 이상합니다 직접 정규식넣는게 나아요

**Comment by E1psycongr00** [comment]
이전 PR에서 해결해서 PR 링크만 올리고 close 해놓을께요
