### ISSUE TITLE
카드 조회 로직 구현

### ISSUE THREAD

**Issue by GounKim** [DHKH-null29/linky_way_back#85]
## 카드 조회 구현
- ### 사용자의 카드 전체 조회
  - GET : /cards/member

- ### 폴더에 해당하는 카드 전체 조회 
  - 조건
    - 레벨 1 & 레벨2 폴더
      - 해당 폴더의 카드만 모두 조회
      - GET : /cards/folder/{folderId}?findDeep=false
    - 레벨 1의 폴더
      -  해당 폴더의 카드와 하위 폴더의 카드 모두 조회
      - GET : /cards/folder/{folderId}?findDeep=true

- ### 태그에 해당하는 카드 전체 조회
  - GET : /cards/tag/{tagid}

**Comment by E1psycongr00** [comment]
음.... 예전에 동석님이랑 회의했던 내용인데 URI 설계시 복수로 응답 받을 수 있는 형태의 객체(컬렉션)는 복수형으로 써주셔야 됩니다  member -> members,  folder -> folders,  tag -> tags

만약 바꾼다면 제 개인적인 의견으로는
사용자 카드 조회 -> /cards/all
폴더 전체 카드 조회 -> /cards/location/{folderId}/all
태그로 카드 조회.. 음 이부분은 잘 모르겠네요

고운님 시간 되시면 URI 부분도 회의 나누면 괜찮겠네요. 어짜피 멘토님도 한번 보라고 말씀하시기도 했고...

**Comment by E1psycongr00** [comment]
시간 되시면 저희 백엔드 회의 전에 서로 네이버 오픈 API 한번 보고 오는 것도 괜찮겠네요

**Comment by GounKim** [comment]
> 음.... 예전에 동석님이랑 회의했던 내용인데 URI 설계시 복수로 응답 받을 수 있는 형태의 객체(컬렉션)는 복수형으로 써주셔야 됩니다 member -> members, folder -> folders, tag -> tags
> 
> 만약 바꾼다면 제 개인적인 의견으로는 사용자 카드 조회 -> /cards/all 폴더 전체 카드 조회 -> /cards/location/{folderId}/all 태그로 카드 조회.. 음 이부분은 잘 모르겠네요
> 
> 고운님 시간 되시면 URI 부분도 회의 나누면 괜찮겠네요. 어짜피 멘토님도 한번 보라고 말씀하시기도 했고...

이 부분 진행 바로 전에 진행했던 회의에서 uri는 일단 이대로 진행하고 나중에 변경하기로 했던 것 같은데 이번에 진행하자는 말씀이신가요?
말씀하신 부분에 대해서는 복수형으로 수정 진행하겠습니다.

**Comment by E1psycongr00** [comment]
아.... 잠깐 보고 왔는데 API 설계가 불완전하긴 하군요.. 일단 고운님이 하신대로 작성하시고 문서 업데이트 할 때 회의 나누면 될 것 같아요... 고운님 말씀대로 복수형만 일단 맞춰서 해주시면 될 것 같아요..

**Comment by GounKim** [comment]
@E1psycongr00 아 제가 글 달아주신 부분에 대해 잘못 이해했던 것 같아요. 복수형으로 작성하라는 부분에 대해서 
- /cards/member
- /cards/folder/{folderId}
- /cards/tag/{tagid}
이 세 부분다 카드를 복수 반환하는 것이지 member, folder, tag들을 복수 반환하는 것이 아니라 s를 붙이지 않았습니다. 
 
- /cards/member  : 카드들을 맴버로 조회
- /cards/folder/{folderId} : 카드들을 폴더로 조회
- /cards/tag/{tagid} : 카드들을 태그로 조회
라는 의미로 작성한 것인데 변경을 어떻게 해야할지 잘 모르겠네요.
현규님이 말씀하신 **사용자 카드 조회 -> /cards/all** 이 부분은 좋은 것 같아요. 이 외에는 기존의 것도 괜찮은 것 같은데.. 어렵네요.

**Comment by E1psycongr00** [comment]
> @E1psycongr00 아 제가 글 달아주신 부분에 대해 잘못 이해했던 것 같아요. 복수형으로 작성하라는 부분에 대해서
> 
> * /cards/member
> * /cards/folder/{folderId}
> * /cards/tag/{tagid}
>   이 세 부분다 카드를 복수 반환하는 것이지 member, folder, tag들을 복수 반환하는 것이 아니라 s를 붙이지 않았습니다.
> * /cards/member  : 카드들을 맴버로 조회
> * /cards/folder/{folderId} : 카드들을 폴더로 조회
> * /cards/tag/{tagid} : 카드들을 태그로 조회
>   라는 의미로 작성한 것인데 변경을 어떻게 해야할지 잘 모르겠네요.
>   현규님이 말씀하신 **사용자 카드 조회 -> /cards/all** 이 부분은 좋은 것 같아요. 이 외에는 기존의 것도 괜찮은 것 같은데.. 어렵네요.

저도 사실 리소스에 대한 부분은 많이 헷갈리고 어려운데.. 
https://velog.io/@neity16/NodeJS-REST-API 블로그에 예제랑 쉽게 정리해 놓은 글이 있네요.. 엄청 정확한 건 아닌거 같은데 참고하셔서 작성하시면 될 것 같습니다...
저도 공부가 필요한 부분이라
어짜피 다시 다 회의 이후 바꿀 부분이라 고운님이 최대한 생각해서 작성해보시고 API 문서만 보고 회의하기 편하게 API에 URI만 업데이트해주세요..
