### ISSUE TITLE
소셜 패키지 조회

### ISSUE THREAD

**Issue by GounKim** [DHKH-null29/linky_way_back#89]
## 패키지 내부 카드들 조회 = 태그로 카드 조회
- GET : /cards/tag/{tagid} or /cards/package/{tagid}
- tag의 shareable여부 조회 필요
- card의 shareable여부 조회 필요

### 태그 shareabe=false일 때 카드의 shareable=true이면?
카드에 다른 공개된 태그에는 조회가 되도록 한다.

### 태그 shareabe=true일 때 카드의 shareable=false이면?
카드는 공개되지 않음

**Comment by pds0309** [comment]
근데 `GET : /cards/tag/{tagid}/{shareable}` 이 부분의 url 에 약간 의문이 드네요

소셜페이지에서 태그로 검색해서 보여주는 부분은 어차피 공유여부가 `true` 인 애들만 조회되어야 하는데

api 사용자에게 공유 여부 데이터를 받아야할 이유가 없을 것 같습니다

**Comment by GounKim** [comment]
> 근데 `GET : /cards/tag/{tagid}/{shareable}` 이 부분의 url 에 약간 의문이 드네요
> 
> 소셜페이지에서 태그로 검색해서 보여주는 부분은 어차피 공유여부가 `true` 인 애들만 조회되어야 하는데
> 
> api 사용자에게 공유 여부 데이터를 받아야할 이유가 없을 것 같습니다

아, 이 부분은 저도 진행하다가 필요가 없다는걸 알게돼서 이미 제거된 상태입니다..! 반영을 안했네요! 감사합니다 :)

**Comment by E1psycongr00** [comment]
> 카드가 비공개면 당연히 태그 공개여부랑 관계없이 조회되면 안된다고 생각합니다
> 
> 태그가 비공개고 카드가 공개면 어차피 해당 태그로는 검색해도 안나오기 때문에 상관없을 것 같습니다.
> 
> 그래서 2번일 것 같네요

저도 이 의견이 맞는것 같아요
