### ISSUE TITLE
테이블 동기화 및 프로파일 분리

### ISSUE THREAD

**Issue by E1psycongr00** [DHKH-null29/linky_way_back#93]
# 요구사항

- RDS 적용을 위해 application.yml 분리
    - local(mySql), test(h2), rds(mysql) 이렇게 분리 예정 => mysql, h2로 바꿈
- 문서 테이블 요구사항과 코드 동기화
    - 인덱스 추가
    - schema.sql 제작
    - 데이터 유형 제약조건 추가

**Comment by pds0309** [comment]
local 환경에서의 경우 직접 pc 의 mysql 을 이용해야한다는 것인지 궁금합니다

**Comment by E1psycongr00** [comment]
> local 환경에서의 경우 직접 pc 의 mysql 을 이용해야한다는 것인지 궁금합니다

네 맞아요 !.. 그렇게 생각하고 있어요..
